#!/bin/bash
ip=$1
port=$2
if [ "x$ip" == "x" ]; then
	ip="10.0.0.4"
fi
if [ "x$port" == "x" ]; then
	port=8082
fi
echo "export HTTP_PROXY=http://$ip:$port"
echo "export http_proxy=http://$ip:$port"
echo "export HTTPS_PROXY=http://$ip:$port"
echo "export https_proxy=http://$ip:$port"
