#!/bin/bash

STORED_CONFIG_FILE=/root/kernel/config

rebuild_post(){
	# rebuild third party kernel modules
	emerge -1 bbswitch nvidia-drivers
}

case $1 in
config)
	cd /usr/src/linux
	cp "${STORED_CONFIG_FILE}" .config
	make oldconfig
	make menuconfig 
	dialog --yesno "Use new config?" 5 20 && cp .config "${STORED_CONFIG_FILE}"
	clear
	;;
rebuild)
	# remove existing kernel
	rm /boot/vmlinuz*
	rm /boot/config*
	rm /boot/System.map*
	rm -rf /lib/modules/*
	# clean source directory
	cd /usr/src/linux
	make mrproper
	# copy kernel config file
	cp "${STORED_CONFIG_FILE}" .config
	# build and install
	make -j5
	make install
	make modules_install
	# regenerate grub.cfg
	ln -s $(findmnt -n -s / -o SOURCE) /dev/root
	grub2-mkconfig -o /boot/grub2/grub.cfg
	# do rebuild_post
	rebuild_post
	;;
*)
	echo "Bad parameter" >&2
	exit 1
	;;
esac
